### PR TITLE
cleanup: use rspec's type matcher

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by sodabrew** [comment]
In a couple places, you switch from `be_kind_of Foo` to `be_instance_of Foo`. What's the difference?

**Comment by tamird** [comment]
`instance_of` is more strict; it won't match subclasses.

**Comment by sodabrew** [comment]
Ah, nice summary at https://www.relishapp.com/rspec/rspec-expectations/v/2-0/docs/matchers/type-check-matchers - ok this makes sense. Would you rebase?

**Comment by tamird** [comment]
rebased

**Comment by sodabrew** [comment]
Love it when tests are green!

**Pull request merged**
