### PR TITLE
Prepared statement support

### PR DESCRIPTION
**Pull request by nyaxt**
Using prepared statement is an effective way to prevent injection attacks and improve performance.
I tried to continue the work on the 'stmt' branch.

Now, I think its basically done but for two caveats:
1. Query results are cached expect for streaming queries.
2. There are no syntax to pass query_options when PreparedStatement#execute. I don't have an idea for nice syntax.

### CODE REVIEW

**Comment by rdp** [comment]
Link to new PR possible please, just for us followers still wondering if mysql2 has preparedstatement support or not?

**Comment by justincase** [comment]
@rdp PR #591

**Comment by justincase** [comment]
#591 has been merged into master.
@sodabrew I think we can close this PR?

**Comment by sodabrew** [comment]
I was just about to ask you this - in a comment on 558, https://github.com/brianmario/mysql2/pull/558#issue-48186012, you mentioned that you'd imported the work from this branch  "... up to 50a7054. Most notably, his [nyaxt's] work on returning Mysql2::Result from Mysql2::Statement#execute is missing." - so I wanted to check on the work from 50a7054..f481190.

Based on a diff I just read through, it looks like you did get everything from this branch?

**Comment by justincase** [comment]
Correct, I continued working on nyaxt patches a long the way. Master diverged a lot since this PR so not all commits were apply 'as-is'. All functionality should be there however.

**Comment by sodabrew** [comment]
This is just tremendous. Thank you again.

**Pull request closed without merging**
