### PR TITLE
[clean] prepared statements

### PR DESCRIPTION
**Pull request by justincase**
The master branch has diverged quite a bit since the original prepared statement commits by tenderlove, brianmario, and nyaxt. I've gone through most of the original commits and wrangled them to fit a clean branch. Tests pass with each commit.

APIs featured:

`Mysql2::Client#prepare(query) # => Mysql2::Statement`
`Mysql2::Statement#execute(*params) # => Mysql2::Statement`
`Mysql2::Statement#param_count # => Integer`
`Mysql2::Statement#field_count # => Integer`
`Mysql2::Statement#fields # => Array[String]`

This PR includes commits from nyaxt up to 50a7054299e08af1356ffae80fda13301a5a882f. Most notably, his work on returning `Mysql2::Result` from `Mysql2::Statement#execute` is missing.

This PR supersedes others and gives us a clean slate to work from.

### CODE REVIEW

**Comment by gaurish** [comment]
Monthly *bump*

Any idea when this will get merged?

**Comment by sodabrew** [comment]
Now that 0.3.18 is out, this is at the top of my mysql2 gem todo list!

**Comment by justincase** [comment]
Excellent! Let me know if there's anything I could help with.

**Comment by sodabrew** [comment]
I took a stab at rebasing this again locally but it was harder than I expected! I wonder if it would make sense to roll-up some of the smaller commits per author at this point.

**Comment by justincase** [comment]
Story continues in PR #591.

**Pull request closed without merging**
