### PR TITLE
Fix :cache_rows => false on prepared statements

### PR DESCRIPTION
**Pull request by ajaska**
Simple fix for part of #736.

Code style might not how you like it, so feel free to comment/request changes/completely redo it yourself etc.

### CODE REVIEW

**Comment by sodabrew** [comment]
Does #741 end up resolving this issue, or should this be merged as well @kamipo ?

**Comment by sodabrew** [comment]
Yep, the test in the first commit triggers a crash. The second commit (forcing cacheRows = 1 for prepared statements) prevents the crash.


```
Mysql2::Statement
/Users/aarons/git/mysql2-sodabrew/spec/mysql2/statement_spec.rb:135: [BUG] Segmentation fault
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0038 p:---- s:0154 e:000153 CFUNC  :each
c:0037 p:---- s:0152 E:000ca0 CFUNC  :to_a
c:0036 p:0010 s:0149 e:000148 BLOCK  /Users/aarons/git/mysql2-sodabrew/spec/mysql2/statement_spec.rb:135 [FINISH]
```

**Comment by kamipo** [comment]
This fixes the another following problem:

```ruby
require 'mysql2'

client = Mysql2::Client.new(
  host: 'localhost',
  username: 'root',
  database: 'mysql',
)

client.query_options.merge!(cache_rows: false)

begin
  stmt = client.prepare('SELECT ?')
  result1 = stmt.execute(1)
  result2 = stmt.execute(2) # result1 is staled
  p result1.to_a            # raise an error
  p result2.to_a
rescue
  p $! #<Mysql2::Error: Attempt to read a row while there is no result set associated with the statement>
end
```

Result:

```
$ bundle exec issue_737.rb
/Users/kamipo/src/github.com/brianmario/mysql2/lib/mysql2/statement.rb:8: warning: :cache_rows is forced for prepared statements (if not streaming)
/Users/kamipo/src/github.com/brianmario/mysql2/lib/mysql2/statement.rb:8: warning: :cache_rows is forced for prepared statements (if not streaming)
issue_737.rb:15: warning: :cache_rows is forced for prepared statements (if not streaming)
#<Mysql2::Error: Attempt to read a row while there is no result set associated with the statement>
```

**Comment by sodabrew** [comment]
The expect-to-output test is unfortunately failing on the 1.8.7 and ree runners:

```
  1) Mysql2::Statement should warn but still work if cache_rows is set to false
     Failure/Error: expect { result = statement.execute.to_a }.to output(/:cache_rows is forced for prepared statements/).to_stderr
     
       expected block to output /:cache_rows is forced for prepared statements/ to stderr, but output nothing
       Diff:
       @@ -1,2 +1,2 @@
       -/:cache_rows is forced for prepared statements/
       +""
```

**Comment by sodabrew** [comment]
@cbandy In 890345e0e4d0829f3656ae9c79fc6dc021c30571 you used a StringIO wrapper to implement stderr output checking -- any concerns if I switch that over to RSpec's output matchers? Did your PR at that time have Ruby 1.8.7 test failures that you did any special workarounds for?

**Comment by cbandy** [comment]
> In 890345e you used a StringIO wrapper to implement stderr output checking -- any concerns if I switch that over to RSpec's output matchers?

No objections from me.

> Did your PR at that time have Ruby 1.8.7 test failures that you did any special workarounds for (was the StringIO wrapper a Ruby 1.8.7 output matcher workaround)?

Not that I recall. I probably depended on Travis to tell me about versions other than the one I had on my workstation at the time.

**Comment by cbandy** [comment]
In fact, I probably stopped here after my search for "rspec test warnings": http://stackoverflow.com/a/5449942

**Pull request merged**
