### PR TITLE
Add an OpenSSL directory configuration option

### PR DESCRIPTION
**Pull request by sodabrew**
CI: Use on MacOS to pick up the correct OpenSSL version. Updates #1301 and #1299

cc @junaruga

### CODE REVIEW

**Comment by sodabrew** [comment]
Need one more edit here, which is that `dir_config('openssl')` should only activate if specified on the command line, otherwise assume the defaults are OK.

**Comment by junaruga** [comment]
Thanks for the PR! I see this PR is better than mine. Just I have a small proposal in my quick review. With the modification below, I was able to pass the tests without MacOS specific condition: `which brew`.

```
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
index b76f91a..b224242 100644
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,7 +27,6 @@ jobs:
           - '2.2'
           - '2.1'
         db: ['']
-        ssl: ['']
         include:
           # Comment out due to ci/setup.sh stucking.
           # - {os: ubuntu-18.04, ruby: 2.4, db: mariadb10.1}
@@ -63,4 +62,6 @@ jobs:
         run: echo 'DB=${{ matrix.db }}' >> $GITHUB_ENV
       - run: sudo echo "127.0.0.1 mysql2gem.example.com" | sudo tee -a /etc/hosts
       - run: bash ci/setup.sh
-      - run: bundle exec rake spec -- $([ -x "$(which brew)" ] && echo --with-openssl-dir=$(brew --prefix ${{ matrix.ssl }}))
+      - run: echo "rake_spec_opts=\"--with-openssl-dir=$(brew --prefix ${{ matrix.ssl }})\"" >> $GITHUB_ENV
+        if: matrix.ssl
+      - run: bundle exec rake spec -- $rake_spec_opts
```

**Comment by sodabrew** [comment]
I made a change in the second to last commit, if you rebase your test branch you'll see `if with_config('openssl')` changes to `if with_config('openssl-dir')`

**Comment by junaruga** [comment]
OK! After rebasng my test branch, I was able to pass the [CI](https://github.com/junaruga/mysql2/actions/runs/3962191688/jobs/6788538080#step:8:10) with the modification above. 😄

**Pull request merged**
