### PR TITLE
Adding support for MYSQL_ENABLE_CLEARTEXT_PLUGIN flag

### PR DESCRIPTION
**Pull request by denisenkom**
This will allow usage of AWS IAM user login for MySQL database

### CODE REVIEW

**Comment by denisenkom** [comment]
Will take a look

**Comment by sodabrew** [comment]
+1 for @jeremy's suggestion, that approach will be consistent with the other connection hash optoins.

@denisenkom take a look at the block of code at https://github.com/denisenkom/mysql2/blob/master/lib/mysql2/client.rb#L34-L44 – The pattern there is each of the hash keys from the connections hash maps onto a setter method, and each setter method is a wrapper around `_mysql_client_options` with the value conversion needed for the Ruby VALUE to the C argument, for example:

```
$ grep -r _mysql_client_options ext/
ext/mysql2/client.c
...
1204:  return _mysql_client_options(self, MYSQL_OPT_RECONNECT, value);
1208:  return _mysql_client_options(self, MYSQL_OPT_LOCAL_INFILE, value);
1218:  return _mysql_client_options(self, MYSQL_OPT_CONNECT_TIMEOUT, value);
...
```

**Comment by denisenkom** [comment]
Agree, updated PR with new code, please take a look.

**Comment by sodabrew** [comment]
Looks good, thanks for the quick turnaround from feedback! Will merge if the tests all run green; is there a reasonable way to unit-test this with the MySQL installed on Travis CI?

I'll need to figure out the timing for when I get a release out, whether it's 0.4.7 or 0.5.0 next to include this.

**Comment by denisenkom** [comment]
I can't think of a way to test this in Travis CI instance.  I did test it with our RDS MySQL instance with IAM authentication plugin enabled.

**Comment by marutosi** [comment]
I have created #866.

**Pull request merged**
