### PR TITLE
Support ruby GC compaction

### PR DESCRIPTION
**Pull request by fatkodima**
ruby 2.7+ introduced GC compaction via `GC.compact`. This PR helps this gem to be compaction friendly.

### CODE REVIEW

**Comment by sodabrew** [comment]
Thank you very much for this! I will read up on compaction to learn more about it! Very likely I want to delay landing this until after the pending 0.5.x release so that there's a new stable version folks could fall back to in case of any instability caused by this change.

**Comment by sodabrew** [comment]
@tenderlove This looks good to me! Any review notes at your end?

**Comment by sodabrew** [comment]
Sorry about the very long delay. Would you mind rebasing since merging the #1284 made some minor conflicting changes? (If you don't have time I'll swing back to this and adjust in a fixit commit.)

**Comment by fatkodima** [comment]
@sodabrew Rebased.

**Pull request merged**
